### ISSUE TITLE
Add the option to disable server restart notifications

### ISSUE THREAD

**Issue by Gusarovv** [neotan/vscode-auto-restart-typescript-eslint-servers#5] opened 2023-07-19 09:19 UTC
Please add it so that I can choose whether to notify or not about the server restart.

**Comment by neotan** [comment] 2023-07-20 01:50
Duplicate of #1

**Comment by neotan** [comment] 2023-07-20 19:50
Thanks for the issue,  @Gusarovv, the enhanced version had been released, pls update to `v0.0.5` and let me know if it works. Thanks!
https://marketplace.visualstudio.com/items?itemName=neotan.vscode-auto-restart-typescript-eslint-servers

**Closed by neotan** 2023-07-20 19:50 UTC

**Comment by Gusarovv** [comment] 2023-07-21 18:09
Thanks! I updated the version to v0.0.5. Disabled the notification - it works fine
